// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Repo's notice under the new-conversation box: the roadmaps in it that
 * nothing is driving.
 *
 * One notice per Repo with its roadmaps inside, rather than one per roadmap —
 * what the human reads first is which repository has work left lying about,
 * and a repository with three of them is one thing to look at rather than
 * three.
 *
 * Nothing here is stored. Every field is read off the repository at the moment
 * the list is drawn, which is why a roadmap somebody has since picked up
 * simply stops appearing rather than having to be taken off anything.
 */
export type AbandonedRepo = { 
/**
 * Which Repo, by the id a Conversation is started against.
 */
repo_id: number, 
/**
 * And what it is called, which is what the notice says.
 */
repo: string, 
/**
 * The roadmaps in it with a stage that could be started now. Never empty:
 * a Repo with nothing to adopt has no notice at all.
 */
roadmaps: Array<AbandonedRoadmap>, };

/**
 * One abandoned roadmap, named with the stage that would be adopted.
 *
 * The stage is the lowest-numbered unchecked one, which is the roadmap's own
 * order rather than anybody's choice — see the abandoned rule in the server's
 * `stages` module.
 */
export type AbandonedRoadmap = { 
/**
 * Its directory name under `docs/roadmaps/` — `mvp`. The roadmap's
 * identity, here as everywhere else.
 */
name: string, 
/**
 * What the roadmap calls itself in its heading, or empty where it has
 * none. Prose about itself, riding along beside the name.
 */
title: string, 
/**
 * The next stage's number as the roadmap writes it — `04`.
 */
stage: string, 
/**
 * And what that stage is called.
 */
stage_title: string, };

/**
 * What became of pressing Adopt.
 *
 * Named the way [`GrillingStarted`]'s refusals are, and for the same reason: a
 * human is at the workbench pressing the button, and each of these is
 * something different for them to go and do. What is decided while nobody is
 * watching says itself on a Timeline instead — see the server's `continuing`
 * module, which starts the same stage by the other route.
 */
export type Adopted = "Adopted" | "NoSuchConversation" | "NotDrafting" | "NotAdopting" | "NoGrillingProfile" | "NoImplementationProfile" | "ProfileBroken" | "FetchFailed" | "NoBaseCommit" | "NoRoadmap" | "RoadmapComplete" | "NoBrief" | "StageInFlight" | "BranchExists" | "WorktreeRefused";

/**
 * The stage an adoption would start, named.
 */
export type AdoptedStage = { 
/**
 * Its number as the roadmap writes it — `04`.
 */
label: string, 
/**
 * And what the roadmap calls it.
 */
title: string, 
/**
 * Where its brief is in the repository, which is the document the work
 * starts from.
 */
brief_path: string, 
/**
 * The branch the stage would be worked on: its own slug, as the unattended
 * path names one. The Conversation's server-invented name is discarded at
 * the press, so this is the name to say rather than that one.
 */
branch: string, };

/**
 * What a Conversation is adopting, as its own page draws it: the roadmap it
 * was started for, and the stage adopting would start.
 *
 * Read off the repository at the Conversation's base commit every time the
 * page is, rather than kept: the roadmap is the repository's document, and
 * only the name of it is Verkstead's. So a base commit the human overrides is
 * answered by the stage that is next *there*, which is the whole reason the
 * stage is not carried over from the notice that was clicked.
 */
export type AdoptionView = { 
/**
 * Its directory name under `docs/roadmaps/` — `mvp`. The one thing about
 * the roadmap that is stored, and the one thing that is true whatever the
 * base commit says.
 */
roadmap: string, 
/**
 * What the roadmap calls itself in its heading at that commit, or empty
 * where it has none — and where the roadmap is not there to read.
 */
title: string, 
/**
 * The stage adopting would start: the lowest-numbered unchecked one, read
 * at the base commit.
 *
 * `null` where there is none to start there — the roadmap is finished, or
 * gone, or its next stage is somebody else's already. The press says which
 * of those it is; this is only what the page can name.
 */
stage: AdoptedStage | null, };

/**
 * A session's output as the Timeline shows it: how far its conversation has
 * got, the last thing that was said, and whether more is coming.
 *
 * The summary and not the Capture. A grilling session prints megabytes over
 * an hour, and the Timeline is re-read every time an open page hears the world
 * moved — so what a Conversation carries is these two lines, and the Capture
 * is fetched by the pane that shows it.
 */
export type AgentOutputEvent = { id: number, 
/**
 * When the session started, RFC 3339.
 */
at: string, 
/**
 * How many lines it has printed.
 */
lines: number, 
/**
 * How many turns its conversation has taken, as the Transcript pane draws
 * them — which is the metric the row and the pane show.
 *
 * `null` where the session keeps no log, and the two places that show this
 * show nothing at all rather than a zero: a session with no Transcript has
 * no turns to be wrong about. Not the same as a count of none, which is a
 * session that has a log and has not said anything into it yet.
 */
turns: number | null, 
/**
 * The last thing the agent said, off its own log — or, where it kept none,
 * the last line it printed with the terminal's control sequences taken
 * out. Empty where it has said nothing yet.
 */
latest: string, 
/**
 * Whether the session writing this is still running.
 *
 * Not something the record holds: a running session is a process, and what
 * knows about one is the server that started it. A Verkstead that has been
 * restarted has no sessions, which is why this is read off what is running
 * rather than off what was written.
 */
running: boolean, 
/**
 * And whether that session has stopped printing — quiet long enough for
 * the mark to say it is sitting there rather than working.
 *
 * Beside `running` rather than instead of it, because the two are
 * different questions and a page draws three answers from them: no mark,
 * a turning ring, and a still one. Always `false` where nothing is
 * running, which is what makes those three the only ones there are.
 *
 * Computed on every read, off the same clock that ends a session that has
 * gone quiet — so a page opened onto a session that has been idle for an
 * hour says so at once rather than waiting to be told.
 */
idle: boolean, };

/**
 * Which coding agent a Profile runs.
 *
 * One value. It is on the wire so that a second backend is a variant added
 * beside `Claude` rather than a field the viewer has to start being told about.
 */
export type AgentType = "Claude";

/**
 * One question's slot in a Response: either an Answer — a selected Option
 * and/or free text — or the Unanswered marker, saying the human chose to
 * leave the question open.
 */
export type Answer = { 
/**
 * The question this resolves, by the name it answers to: `Q7` for a
 * Question, `Q7a` for a Sub-question.
 */
label: string, 
/**
 * The number of the Option the human picked.
 */
selected?: number | null, 
/**
 * What the human wrote in their own words, alongside or instead of an
 * Option.
 */
free_text?: string | null, 
/**
 * Left open on purpose. Exclusive with an Answer: the agent must treat
 * the question as still open.
 */
unanswered?: boolean, };

/**
 * A Set's Response as the page needs it: the Answers, and when they were sent.
 */
export type Answered = { submitted_at: string, response: Response, };

/**
 * What the API returns when it refuses a request.
 */
export type ApiError = { 
/**
 * One line saying what was refused.
 */
error: string, 
/**
 * The grammar violations behind the refusal, each naming its question.
 * Empty when the request failed for some other reason.
 */
violations?: Array<Violation>, };

/**
 * A Question or a Sub-question as the page draws it: the name it answers to,
 * its text already rendered, and the Options it offers.
 *
 * One type for both, because the page asks them the same way and the schema's
 * distinction between them is spent by the time it gets here: a Sub-question's
 * name is its parent's label and its letter, resolved on the way out.
 *
 * The form is built from the Options' numbers and their Recommendation flags,
 * and a Response answers by number.
 */
export type AskView = { 
/**
 * `Q7` for a Question, `Q7a` for a Sub-question.
 */
name: string, 
/**
 * The text as HTML, rendered and sanitized by the server on the way out.
 */
text_html: string, 
/**
 * The axes the Options are compared along, each already inline HTML, in the
 * order the agent declared them. Empty on a question that declared none —
 * which is what tells the page to draw the list rather than the table, so
 * the two never have to be told apart by looking at the Options.
 *
 * Rendered here beside everything else the agent wrote, so the browser
 * still needs no markdown parser to draw a header.
 */
columns: Array<string>, options: Array<OptionView>, };

/**
 * Who a session's commits are by.
 *
 * Two strings rather than two optionals, empty where nothing is configured:
 * the form holds them that way, and half an author is a real state — a name
 * with no address is what git complains about by name.
 */
export type Author = { name: string, email: string, };

/**
 * The branch to come off, or `null` to go back to the default-branch rule.
 */
export type BaseBranchChoice = { 
/**
 * One of the repository's own branches, local or remote-tracking, by name.
 * Stored as the name and resolved when grilling starts, so the work comes
 * off wherever that branch stands then.
 */
branch: string | null, };

/**
 * What became of choosing the branch the work comes off.
 */
export type BaseRecorded = "Recorded" | "NoSuchConversation" | "NotDrafting" | "NoSuchBranch";

/**
 * One line of the backend's own bookkeeping.
 */
export type Bookkeeping = { 
/**
 * The line's place among the bookkeeping, counted from 1 — its own count,
 * not the conversation's.
 */
id: number, 
/**
 * What the log called it.
 */
kind: string, 
/**
 * The line itself.
 */
line: string, };

/**
 * What the branch is to be called.
 */
export type BranchRename = { branch: string, };

/**
 * What became of naming the branch.
 */
export type BranchRenamed = "Renamed" | "NoSuchConversation" | "NotDrafting" | "NotABranchName";

/**
 * A Brief as the human has just written it.
 */
export type BriefEdit = { markdown: string, };

/**
 * The Brief as the page receives it: rendered for reading, and as it was
 * written for editing.
 */
export type BriefEvent = { id: number, 
/**
 * When it was written, RFC 3339.
 */
at: string, 
/**
 * The markdown the human last wrote, for the field they write it in.
 */
markdown: string, 
/**
 * The same, as HTML — rendered and sanitized by the server on the way out.
 */
html: string, 
/**
 * Whether this Brief is done being written: the round it belongs to has
 * been grilled, so it is the record of what that round was built from
 * rather than a document to edit.
 *
 * The server's rule rather than something the page works out from the
 * Conversation around it, as `ready_to_grill` is — and it is a fact about
 * one Brief rather than about the Conversation, because a Conversation gets
 * one Brief per round and what is true of them differs: an adopting
 * Conversation's first Brief is frozen from the start — it is the stage
 * brief, and nobody here writes it.
 */
frozen: boolean, };

/**
 * What became of an edit to a Brief.
 */
export type BriefSaved = "Saved" | "NoSuchConversation" | "NotDrafting";

/**
 * Why a saved Profile cannot be run under as things stand.
 *
 * Not a way of being saved: every Profile here passed the same checks when it
 * was written down. This is what has become of its pair since.
 */
export type Broken = "DirMissing" | "ConfigMissing" | "OutsideWatchedPaths";

/**
 * One session's Capture, whole, as the details pane receives it.
 *
 * Byte for byte, control sequences and all: what a terminal was sent is what a
 * session said, and a Capture that had been tidied up would be a record of
 * something else.
 *
 * Not quite all of it is the agent's own word. What bwrap says when it will
 * not start is said on the terminal Verkstead began it on, so it arrives here
 * too, where it happened and in among whatever else was printed. On a session
 * that never started it is the only account of why — which makes the Capture
 * the place for it, being where somebody looking at a session that said
 * nothing is already looking.
 */
export type Capture = { text: string, };

/**
 * A commit as the Timeline shows it: what it was called, and how much of the
 * repository it moved.
 *
 * The line and not what is behind it. A commit's summary and its diff are what
 * the details pane fetches — see [`CommitPane`] — and the Timeline is re-read
 * every time an open page hears the world moved.
 *
 * There is no state here and no action on it. Commits are viewable and nothing
 * else: the design gives them no per-commit review, because feedback about the
 * work consolidates in the wrap-up phase.
 */
export type CommitEvent = { id: number, 
/**
 * When it reached the Timeline, RFC 3339. Which is when Verkstead noticed
 * it rather than when it was committed — the two are a poll apart, and the
 * Timeline is a record of what Verkstead saw happen.
 */
at: string, 
/**
 * The full hash. Full, because what it takes for a short one to be
 * unambiguous grows with the repository — the page shortens it for
 * reading, which is a different thing from recording one shortened.
 */
sha: string, 
/**
 * The first line of the commit message.
 *
 * It comes from the Event because it cannot come from the diff: the diff
 * arrives headerless, which is what lets it be rendered by the same
 * renderer an attached Diff is.
 */
subject: string, files: number, insertions: number, deletions: number, 
/**
 * What the commit said about itself, as prose alone: its Commit Summary
 * flattened to a line with the Diagram left out, for the card to clamp —
 * see [`crate::markdown::to_prose`].
 *
 * The prose and not the rendering, unlike every other document on a card.
 * A commit's card is a button, rendered markdown cannot live inside one,
 * and the summary is on the card to be read rather than to be read *at*:
 * what it looks like whole is the pane's, and the card says what it says.
 *
 * `None` where the commit carried no summary — which is every bookkeeping
 * commit and every commit recorded before summaries were kept — and where
 * what it carried was a Diagram and nothing else. Both draw the card that
 * has always been drawn.
 */
snippet: string | null, };

/**
 * One commit, as the details pane receives it: what it said about itself, and
 * what it changed.
 *
 * Its own request rather than a field on the Conversation, for the reason a
 * Capture is: a Timeline is read every time an open page hears the world
 * moved, and a commit is read whole when somebody opens the one Event it
 * belongs to.
 *
 * The diff is rendered with the folds and the highlighting an attached Diff
 * already gets, because it is the same renderer on the same kind of input — see
 * [`crate::diff`].
 */
export type CommitPane = { 
/**
 * The Commit Summary, rendered and sanitized like every other document an
 * agent wrote — `null` where the commit carried none, which is every
 * bookkeeping commit and every commit recorded before summaries were kept.
 */
summary: string | null, 
/**
 * Whether that summary came out holding a Diagram, and so whether the pane
 * carries the client-side renderer at all.
 *
 * Answered here, off the HTML above, exactly as a Set's own flag is — see
 * [`crate::SetView::diagrams`]. It travels with the pane because it is a
 * fact about this commit's own account of itself, and because mermaid is
 * megabytes: the pane that asks for the bundle is the one with something to
 * draw with it. `false` where there is no summary, there being nothing
 * there to hold a Diagram.
 */
diagrams: boolean, 
/**
 * `null` where the commit changed nothing a diff can show, which is a merge
 * or an empty commit. A commit the repository no longer has is not this: it
 * is a 404, because there is nothing there to draw a pane about.
 */
diff: DiffView | null, };

/**
 * And what became of archiving one: putting a Closed Conversation away, so the
 * sidebar stops drawing it.
 *
 * Reversible, which is why nothing here is confirmed and why the refusals are
 * so mild: the worst of them says the human asked for something that is already
 * true.
 */
export type ConversationArchived = "Archived" | "AlreadyArchived" | "NotClosed" | "NoSuchConversation";

/**
 * What became of closing one.
 */
export type ConversationClosed = "Closed" | "AlreadyClosed" | "NoSuchConversation" | "WorktreeStuck";

/**
 * One row of the conversations sidebar.
 *
 * The branch is the row's name: a Conversation has no title of its own, and of
 * what it does have the branch is the short line the human chose.
 *
 * Where it has got to is drawn rather than worded — a turning ring for a
 * session getting on with it, the same ring empty for one that has gone quiet,
 * a dot for a Conversation that wants answering, a dotted border for a draft
 * and a dimmed card for work that has stopped. Which is why the facts below are
 * facts and not one collapsed verdict: the row says what is true of the
 * Conversation, and which mark that comes out as is the one rule the viewer
 * keeps.
 */
export type ConversationEntry = { id: number, branch: string, 
/**
 * What the Repo this Conversation is against is called.
 */
repo: string, state: Lifecycle, 
/**
 * Whether a session is running on this Conversation right now.
 *
 * The server's own registry of running processes and nothing else, so a
 * server that restarted says no about work it is no longer doing.
 */
working: boolean, 
/**
 * And whether that session has stopped printing — the same quiet the
 * agent-output row's mark is drawn from, said here so that a card and the
 * row it opens tell the same truth about the same session.
 *
 * Always `false` where nothing is working, which is what keeps the two a
 * pair rather than a contradiction: idle is a thing a *running* session
 * is. Which mark it comes out as is the viewer's, and the rule there is
 * unchanged — waiting still wins over both.
 */
idle: boolean, 
/**
 * Whether something about this Conversation is waiting on the human: an ask
 * left open, or driving that has stopped.
 *
 * Folded from every source before it leaves, so the viewer holds no list of
 * them. A Draft is never one of them: it is drawn as a draft, and that is
 * the whole of what a draft has to say.
 */
waiting: boolean, };

/**
 * What became of submitting one.
 *
 * Named the way [`GrillingStarted`]'s refusals are, and nothing here is about
 * the state the Conversation was in: the human has looked at the work and said
 * where it goes, so the source is not something to be refused for. What is left
 * to be wrong about is the *target* — a state whose work cannot be set going
 * from what the record holds.
 */
export type ConversationSteered = "Steered" | "NoSuchConversation" | "NoPullRequest" | "NoInstruction" | "EmptyBrief" | "NoPairing" | "NoSuchProfile" | "NoSuchModel" | "NoBaseCommit" | "WorktreeRefused";

/**
 * What became of pressing Stop or Force stop.
 *
 * One answer for both presses, because they ask for the same thing and differ
 * only in what they will wait for: the run is to stop, and nothing is to be
 * started for this Conversation until Resume is pressed. [`Stopped`] and
 * [`Stopping`] are the two ways that is now true — see each.
 *
 * Named the way [`Resumed`]'s refusals are, and for the same reason: a press
 * that quietly did nothing would leave the human watching a run they thought
 * they had stopped.
 *
 * [`Stopped`]: ConversationStopped::Stopped
 * [`Stopping`]: ConversationStopped::Stopping
 */
export type ConversationStopped = "Stopped" | "Stopping" | "AlreadyStopped" | "NotDriven" | "NoSuchConversation";

/**
 * And what became of taking one back out, which is the way back from it.
 *
 * One refusal fewer than archiving has: there is no state a Conversation can
 * be in that is the wrong one to put back on the list.
 */
export type ConversationUnarchived = "Unarchived" | "NotArchived" | "NoSuchConversation";

/**
 * One Conversation, whole: what it is attached to, what the human has settled
 * about it, and everything that has happened to it.
 */
export type ConversationView = { id: number, 
/**
 * The Repo, in the shape the Repo list already sends one — the workbench
 * shows the same three facts about it, and a second shape for the same
 * thing would be a second opinion about what a Repo is.
 */
repo: RepoEntry, branch: string, 
/**
 * The commit the work will branch from, where the human overrode the rule.
 * `null` is the rule itself: the default branch's tip, as it stands when
 * grilling starts — which is why there is no value here to show instead.
 */
base_commit: string | null, state: Lifecycle, 
/**
 * The Profile and model the grilling session will run under, whole rather
 * than by id: the pane says what they are, and whether the Profile is
 * still runnable.
 */
grilling_pairing: PairingView | null, 
/**
 * And the ones the implementation will run under. Chosen separately
 * because it is genuinely a separate account and model.
 */
implementation_pairing: PairingView | null, 
/**
 * Whether everything needed before grilling will start is settled: both
 * Pairings complete and neither Profile broken, a Brief with something in
 * it, and a Conversation still drafting.
 *
 * The server's rule rather than something the page works out from the
 * fields around it. Every one of the refusals is checked again when the
 * button is pressed — this is what decides whether to offer the button, and
 * what it says is true only as of the moment it was read.
 */
ready_to_grill: boolean, 
/**
 * Whether there is driving to start again: the Conversation is in a state
 * something ought to be driving, and nothing is.
 *
 * What decides whether Resume is offered, and the server's rule rather
 * than something the page works out from the fields around it — *driven*
 * is a register of tasks that are running, and a page cannot see one.
 * Every refusal is checked again when the button is pressed; this says
 * only that it was worth offering as of the moment it was read.
 *
 * A question about a process as much as about the record, so a restarted
 * server reads every Conversation it left mid-run as one to resume —
 * which each of them is.
 */
ready_to_resume: boolean, 
/**
 * And whether there is driving to stop: the Conversation is in a state
 * something ought to be driving, and it has not stopped.
 *
 * What decides whether Stop and Force stop are offered. Not the mirror of
 * [`ready_to_resume`]: a Conversation between one step and the next has
 * both, because nothing is running now and the run is going to launch
 * something the moment it can. A quiet Conversation is one to stop as much
 * as a busy one.
 *
 * Force stop is offered where this and [`working`] are both true — the
 * stop that ends a session is worth offering only where there is one.
 *
 * [`ready_to_resume`]: ConversationView::ready_to_resume
 * [`working`]: ConversationView::working
 */
ready_to_stop: boolean, 
/**
 * And whether a steer into Implementing has anything to carry on: the
 * branch holds a backlog with work left in it, or a roadmap it has
 * written.
 *
 * What decides whether the steer modal offers *carrying on* — the target
 * itself is offered on every Conversation there is, because an instruction
 * can always be written. Where this is false the instruction is the whole
 * of what that target can be, so the modal requires one.
 *
 * The server’s rule rather than something the page works out from the
 * fields around it: what stands is a reading of the Worktree as it is now,
 * which a page cannot make. Read the same way everything else pinned to
 * the Timeline is.
 *
 * **A Worktree that has gone is not a branch holding nothing**, and this is
 * true there. There is no directory to read, and the steer checks one out
 * of the branch before anything runs in it — so a Conversation stuck behind
 * a deleted directory is offered the carrying on its branch may well hold,
 * and what decides it in the end is the relaunch that reads the directory
 * the steer has just made.
 *
 * Checked again when the modal is submitted, as every refusal here is;
 * this says only that it was worth offering as of the moment it was read.
 */
ready_to_continue: boolean, 
/**
 * What this Conversation is adopting, where it is adopting anything.
 *
 * `null` is the ordinary Conversation, which begins with a Brief and a
 * grilling. Anything else is one started from the abandoned-roadmaps
 * notice, and it is what puts the page on the adoption shape: the roadmap
 * and its stage named, both Profiles and the base commit to fix, and one
 * Adopt press — no Brief to write and no grilling to start.
 */
adopting: AdoptionView | null, 
/**
 * The worktree the grilling was given to work in, once there is one.
 *
 * `null` both before grilling starts and after closing — the two ways a
 * Conversation has none, which are the same fact about it.
 */
worktree: Worktree | null, 
/**
 * The latest pick: how the human most recently said the work should be
 * built, on a proposal Set of this Conversation's.
 *
 * `null` until a proposal has been put to them and picked on. What the page
 * *draws* of the choice is the answered Set on the Timeline, which is where
 * it was made; this is the fact about the Conversation itself.
 */
direction: Direction | null, 
/**
 * Which Event the Conversation is blocked on, or `null` where nothing is
 * stopping it.
 *
 * What the *blocked on you* badge is drawn from. The Event id and not a
 * flag, so that a header saying the work has stopped can point at the thing
 * that stopped it — a Timeline is long by the time a run gets far enough to
 * stop, and *blocked on you* with nowhere to go would be a badge the human
 * had to go hunting behind.
 *
 * *Blocked on you* is a badge on an active state and never a state of its
 * own, which is why this sits beside `state` rather than in it.
 */
blocked_on: number | null, 
/**
 * What the stop shows about the account that ran out coming back, and
 * `null` on every stop that is not a usage window's — which is nearly all
 * of them, and every Conversation that has not stopped.
 *
 * Words to draw beside Resume rather than a moment anything acts on: no
 * stop resumes itself, so what a stopped run waits for is a press whatever
 * stopped it. The one thing that tells a run stopped by an exhausted window
 * from a run stopped by anything else — same card, same badge, same button.
 *
 * As the session printed it, because the wording is the backend's: `3pm`
 * stays `3pm`, which is what somebody looks at their own clock for.
 */
resets: string | null, 
/**
 * Whether a session is registered for this Conversation as of this read.
 *
 * The same fact the sidebar draws its working indicator from, said here
 * because the Timeline has its own use for it: Force stop is offered
 * exactly where something is running, and the states it is offered in are
 * the ones a session may or may not be running in.
 *
 * A question about a process rather than about the record, so it is true
 * only as of the moment it was read — and a restarted server has no
 * sessions at all, so every Conversation then reads as not working, which
 * is what each of them is.
 */
working: boolean, 
/**
 * Oldest first, which is reading order and puts the Brief at the top.
 */
timeline: Array<TimelineEvent>, 
/**
 * Whether the human has put this Conversation away — see
 * [`ConversationArchived`].
 *
 * What the actions menu offers Unarchive by, in the place Archive stands
 * in on a Closed Conversation that is still on the list. Nothing else on
 * the page turns on it: an archived Conversation is drawn exactly as it
 * was, because being off the sidebar is the whole of what archiving does.
 */
archived: boolean, 
/**
 * The Events that stay in view rather than scrolling past with the record.
 *
 * Apart from the Timeline rather than in it, because that is what pinning
 * *is*: the list is a record of moments, and each of these is the current
 * state of something the work is against. Empty is the ordinary case — a
 * Conversation with no backlog has nothing to pin.
 */
pinned: Array<PinnedEvent>, };

/**
 * The Diff as the browser receives it: the HTML the server rendered, and the
 * path of each file in it, in Diff order — `paths[0]` is what `#diff-1` shows.
 *
 * The two travel together rather than as two fields on the Set, because they
 * describe the same thing and the table of contents is built from both: the
 * nav names the folds from the paths and jumps by their positions, so a nav
 * out of step with the markup would jump to the wrong file. Reading the paths
 * back out of the rendered HTML instead would mean shipping a parser to do it
 * with, and would make the nav a description of the page rather than of the
 * Set.
 */
export type DiffView = { html: string, paths: Array<string>, };

/**
 * One of the three ways the work can be built.
 *
 * Named on the wire in the words the design uses for them, so a Set is
 * readable as written: `inline`, `task-list`, `roadmap`.
 */
export type Direction = "inline" | "task-list" | "roadmap";

/**
 * What became of starting a Conversation grilling.
 *
 * Every refusal is named rather than collapsed into one, because each of them
 * is something different for the human to go and do: choose a Profile, write a
 * Brief, pick another commit, deal with a branch that is already there. A
 * single "cannot start" would leave them guessing which.
 */
export type GrillingStarted = "Started" | "NoSuchConversation" | "NotDrafting" | "NoGrillingProfile" | "NoImplementationProfile" | "ProfileBroken" | "EmptyBrief" | "FetchFailed" | "NoBaseCommit" | "BranchExists" | "WorktreeRefused";

/**
 * The handoff document as the page receives it.
 *
 * HTML alone, unlike the Brief, which travels as its source as well: the Brief
 * is the one document on this wire the human edits, and this one nobody does.
 * It is the agent's account of what was settled, fixed at the moment the
 * grilling ended.
 */
export type HandoffEvent = { id: number, 
/**
 * When it reached the Timeline, RFC 3339.
 */
at: string, 
/**
 * Rendered and sanitized by the server on the way out, as every piece of
 * agent markdown on this wire is.
 */
html: string, };

/**
 * Where a Conversation has got to.
 *
 * The whole ladder, though only the first two are reachable yet: the states are
 * the domain's, and the page says which one a Conversation is in rather than
 * assuming the only one it can currently be.
 */
export type Lifecycle = "Draft" | "Grilling" | "Implementing" | "Wrapping" | "Done" | "Closed";

/**
 * What a Set still waiting on the human says about itself: whether an agent is
 * currently waiting on it, whether nothing is holding a wait any more, or
 * whether nothing ever was.
 *
 * Display state only (ADR-0001). A disconnected Set is still answerable and is
 * never withdrawn on its own — the CLI reconnects through transient drops, and
 * only a human may lock a Set whose agent is really gone.
 *
 * It is a verdict rather than a timestamp because the server has the clock and
 * the registry of held waits; the browser only draws what it is told.
 */
export type Liveness = "waiting" | "disconnected" | "deferred";

/**
 * What became of the human closing a Set unanswered.
 */
export type Locked = "Closed" | "AlreadyAnswered" | "AlreadyLocked" | "NoSuchSet";

/**
 * A Manual Task as the page receives it: what was asked for, and when.
 *
 * HTML alone, like the Notice beside it and unlike the Brief: it is a moment on
 * the record rather than a document anybody goes back and edits.
 */
export type ManualTaskEvent = { id: number, 
/**
 * When it was asked for, RFC 3339.
 */
at: string, 
/**
 * Rendered and sanitized by the server on the way out, as every piece of
 * markdown on this wire is.
 */
html: string, };

/**
 * A move as the page receives it: when, and to what.
 *
 * No rendered body, unlike the Brief — there is no markdown in a move. What the
 * Timeline draws is a sentence of the viewer's own making from the one state,
 * because the wording belongs to whoever is reading it rather than to the
 * record.
 */
export type MovedEvent = { id: number, 
/**
 * When it moved, RFC 3339.
 */
at: string, state: Lifecycle, };

/**
 * Starting one to adopt a roadmap with: which Repo, and which of its roadmaps.
 *
 * What the notice sends when a roadmap in it is clicked. The roadmap is named
 * by its directory under `docs/roadmaps/`, which is its identity here as
 * everywhere else — the stage is not sent, because which stage is next is the
 * roadmap's own answer at whatever commit the Conversation ends up branching
 * from.
 */
export type NewAdoption = { repo_id: number, roadmap: string, };

/**
 * Starting a Conversation: the Repo it is against, and nothing else.
 *
 * The branch name is not the browser's to send. It is prefilled randomly, and a
 * prefill the page invented would be one the server never saw — the record is
 * the server's from the moment it exists.
 */
export type NewConversation = { repo_id: number, };

/**
 * The order the human has just dragged the sidebar into: every Conversation
 * they can see, by id, top first.
 *
 * The whole list rather than the one row that moved, because the whole list is
 * what a drag produces and what the human is looking at when they let go. A
 * move said as *this one, to there* would have to be replayed against a list
 * the server might have added to since; a list said whole is simply what they
 * meant.
 */
export type NewOrder = { order: Array<number>, };

/**
 * A notice as the page receives it: what Verkstead did, and when.
 *
 * HTML alone, like the handoff and unlike the Brief: nobody edits it. Rendered
 * on the way out all the same, because a notice says which stage it started and
 * what the branch is called, and those are worth setting in a code span rather
 * than running into the prose around them.
 */
export type NoticeEvent = { id: number, 
/**
 * When it was said, RFC 3339.
 */
at: string, 
/**
 * Rendered and sanitized by the server on the way out, as every piece of
 * markdown on this wire is.
 */
html: string, };

/**
 * One thing that moved, said as briefly as it can be said.
 *
 * A page too old to know a kind treats it as everything having moved, which is
 * the behaviour every kind used to get — so a new kind is safe to add and an
 * old page stays correct against a newer server.
 */
export type Nudge = { "kind": "transcript", conversation: number, } | { "kind": "screen", conversation: number, } | { "kind": "commit", conversation: number, } | { "kind": "set", conversation: number, } | { "kind": "liveness", conversation: number, } | { "kind": "conversation", conversation: number, } | { "kind": "conversations" } | { "kind": "repos" } | { "kind": "profiles" };

/**
 * One Option as the page draws it: the number a Response answers by, its text
 * already rendered, and whether the agent recommended it.
 *
 * Its text is inline markup and nothing blockier, because an Option is one line
 * beside a radio and the whole row is the tap target: a paragraph or a list
 * emitted inside that label would split the row in two.
 */
export type OptionView = { n: number, 
/**
 * The text as inline HTML, rendered and sanitized by the server on the way
 * out.
 */
text_html: string, recommended: boolean, 
/**
 * This Option's row of the Answer Table, one cell per axis the question
 * declared, in that order, each already inline HTML. Empty wherever the
 * question declared no axes.
 *
 * Inline for the reason `text_html` is: the whole row is the tap target,
 * and a block in one of its cells would break the row apart.
 */
cells: Array<string>, };

/**
 * One of a Conversation's two Pairings, as the page shows it: the Profile
 * whole, and the model paired with it.
 *
 * The Profile whole rather than by id because the pane says what it is and
 * whether it is still runnable — and the model beside it because a Pairing is
 * both halves, and either half alone is not something to launch a session
 * with.
 */
export type PairingView = { profile: ProfileEntry, 
/**
 * The model of that Profile's list this Conversation's sessions run on.
 *
 * `null` is a Profile chosen before pairings existed, which is not a
 * Pairing: the page draws it as nothing chosen, because while the
 * Conversation is drafting that is a choice to make again. One past
 * drafting keeps running on the model its Profile carried, which nothing
 * here has to say — its Pairings are fixed and there is no picking left.
 */
model: string | null, };

/**
 * An Event the Timeline keeps in view rather than letting scroll past.
 *
 * A fixed set — a task list, a stage list and a PR — and no manual pin or
 * unpin: what is pinned is decided by what kind of thing it is, so there is no
 * state here to flip and no route to flip it with. A tagged kind for the reason
 * [`TimelineEvent`] is one: what gets drawn turns on which kind it is.
 *
 * All three are on the record as well, each at the moment it arrived there, and
 * each is one card drawn twice rather than two cards.
 */
export type PinnedEvent = { "TaskList": TaskListEvent } | { "StageList": StageListEvent } | { "PullRequest": PullRequestEvent };

/**
 * Which Profile and model a Conversation is pairing for one of its two roles.
 */
export type ProfileChoice = { profile_id: number, 
/**
 * One of that Profile's models. Never absent: there is no default model
 * anywhere, so a Pairing is picked whole or not at all.
 */
model: string, };

/**
 * What became of choosing one.
 */
export type ProfileChosen = "Chosen" | "NoSuchConversation" | "NoSuchProfile" | "NoSuchModel" | "NotDrafting";

/**
 * What became of removing a Profile.
 */
export type ProfileDeleted = "Removed" | "NoSuchProfile" | "InUse";

/**
 * A Profile as the human has just written it, for saving or for rewriting.
 *
 * No agent type: there is one, and offering a choice of one is theatre. The
 * server records `Claude`, and the field arrives here when there is something
 * to choose between.
 */
export type ProfileEdit = { name: string, 
/**
 * The absolute path of the directory bind-mounted over `~/.claude`.
 */
claude_dir: string, 
/**
 * The absolute path of the file bind-mounted over `~/.claude.json`.
 */
config_file: string, 
/**
 * The models this account can run a session on, in the order they were
 * typed. The form takes them a line apiece; blank lines and repeated
 * whitespace are the server's to drop, and a list that comes to nothing is
 * refused.
 */
models: Array<string>, };

/**
 * One row of the Profile list.
 *
 * The paths are the resolved ones the server recorded rather than whatever was
 * typed to save them: those are what will be bind-mounted, so those are what is
 * worth showing.
 */
export type ProfileEntry = { id: number, name: string, claude_dir: string, config_file: string, 
/**
 * Every model this account can run a session on. At least one, and none of
 * them preferred over the others: the list says what is available and
 * nothing more.
 */
models: Array<string>, agent_type: AgentType, 
/**
 * `null` while the pair is where it was left, which is the ordinary case.
 */
broken: Broken | null, };

/**
 * What became of saving a Profile.
 *
 * The refusals are the server's and not the form's: the Watched Paths are a
 * security boundary, and every request reaching the endpoint is decided there
 * whether or not a form was involved.
 */
export type ProfileSaved = "Saved" | "NoSuchProfile" | "Nameless" | "Modelless" | "NameTaken" | "DirNotAbsolute" | "DirMissing" | "DirOutsideWatchedPaths" | "NotADirectory" | "ConfigNotAbsolute" | "ConfigMissing" | "ConfigOutsideWatchedPaths" | "NotAFile";

/**
 * The grilling's closing proposal as the Set it rides draws it: which direction
 * was recommended, and why.
 *
 * The rationale arrives as HTML like every other piece of agent markdown on this
 * wire — the parser and the sanitizer are the server's.
 */
export type ProposalView = { 
/**
 * The direction the agent recommends, which the chooser marks.
 */
direction: Direction, 
/**
 * Why, rendered and sanitized by the server on the way out.
 */
rationale_html: string, };

/**
 * The agent's prose, rendered.
 */
export type Prose = { 
/**
 * The turn's place in the conversation, counted from 1 — what the viewer
 * reconciles rows by, so a fold opened on one survives a re-read.
 */
id: number, html: string, };

/**
 * One comment on a pull request: who said it, when, and what they said.
 *
 * The body arrives rendered, like everything else an outsider wrote — a comment
 * is markdown, and it is markdown from the public internet, so it is sanitized
 * on this side of the wire rather than put in a page raw.
 */
export type PullRequestComment = { 
/**
 * The login of whoever left it. Empty where the account has gone, which is
 * a comment to draw rather than a reason to refuse the pane.
 */
author: string, 
/**
 * When it was made, RFC 3339, as GitHub stamped it.
 */
at: string, html: string, };

/**
 * One commit of a pull request: what it is, and what it was called.
 *
 * Not a [`CommitEvent`]: that is a commit Verkstead watched land on the branch
 * and put on the Timeline, with counts of what it moved and a diff behind it.
 * This is a line of a list GitHub keeps, and the two can differ — a branch that
 * was rebased after the PR opened has commits on the PR that are on no
 * Timeline.
 */
export type PullRequestCommit = { 
/**
 * The full hash, as everything on this wire carries one: the page shortens
 * it for reading.
 */
sha: string, 
/**
 * The first line of the commit message.
 */
subject: string, };

/**
 * What is on a pull request now: the commits it carries, and what has been said
 * about it.
 *
 * Its own request rather than a field on the Conversation, for the reason a
 * commit's diff is one — and for a further reason of its own: reading this is
 * asking GitHub, over the network, through the host's `gh`. A Timeline that
 * carried it would make an API call every time an open page heard the world
 * moved.
 *
 * Fetched rather than remembered, in the same spirit the task list is read off
 * the Worktree: a PR is being worked on while the human is looking at it.
 */
export type PullRequestDetails = { 
/**
 * Oldest first, as GitHub lists them, which is the order they landed.
 */
commits: Array<PullRequestCommit>, comments: Array<PullRequestComment>, };

/**
 * The pull request as the Timeline shows it: what it is called and what number
 * it answers to, with a way out to GitHub itself.
 *
 * An id and a stamp of its own, unlike the task list beside it, because a pull
 * request is the whole of what it says: the finish step opened one at a moment
 * worth keeping, and the Conversation moved into Wrapping on the strength of
 * it. What is not on the record is what the PR holds — see
 * [`PullRequestDetails`], which the details pane fetches when somebody opens
 * this.
 */
export type PullRequestEvent = { id: number, 
/**
 * When it reached the Timeline, RFC 3339 — which is when Verkstead found
 * it rather than when GitHub opened it, the two being a finish step apart.
 */
at: string, 
/**
 * The number GitHub gave it, which is what everybody calls it by.
 */
number: number, 
/**
 * Its title, which is the feature name the finish step gave it.
 */
title: string, 
/**
 * The whole URL, because merging is the human's act and this is the way to
 * where they do it.
 */
url: string, };

/**
 * The public half of the server's VAPID keypair, base64url-encoded from the
 * uncompressed point — what `PushManager.subscribe` takes as its
 * `applicationServerKey`.
 *
 * The private half stays on the server: this is only how a browser names the
 * server it is subscribing to.
 */
export type PushKey = { key: string, };

/**
 * A turn put to the agent, rendered.
 */
export type Put = { 
/**
 * The turn's place in the conversation, counted from 1.
 */
id: number, html: string, };

/**
 * A Question Set as the Timeline shows it: what it was called, the table of
 * what was asked against what was decided, and where it stands.
 *
 * The table and not the Set. The design gives a Question Set a summary of
 * number, question and answer in the Timeline and the whole document in the
 * details pane, and the two are different sizes: a Set carries a Preface, every
 * Option of every Question and the whole uncommitted Diff of the repository it
 * was asked from, and the Timeline is re-read every time an open page hears the
 * world moved.
 *
 * `set_id` is what the details pane fetches the document by — the same
 * `/api/ui/sets/{id}` the standalone page reads, because it is the same Set
 * reached another way.
 */
export type QuestionSetEvent = { id: number, 
/**
 * When the Set was put, RFC 3339.
 */
at: string, set_id: number, title: string, 
/**
 * One row per Question and Sub-question, in the order the agent asked
 * them.
 */
rows: Array<SetRow>, 
/**
 * Whether it is still waiting on the human, and what became of it if not.
 * The same verdict the Set's own page carries, from the same registry of
 * held waits — this is a Timeline the human answers from.
 */
standing: Standing, };

/**
 * One Question as the page draws it, with its Sub-questions nested one level
 * under it.
 */
export type QuestionView = { ask: AskView, subquestions: Array<AskView>, 
/**
 * Whether this Question is a Heading — Sub-questions under it and no
 * Options of its own — and so heads them rather than asking anything. The
 * page draws its text without a field, and no Answer comes back for it.
 *
 * Answered here rather than worked out in the browser from the Options and
 * Sub-questions beside it, so that the page and the grammar that refuses a
 * Response cannot come to different readings of the same Set.
 */
heading: boolean, 
/**
 * The Question's own text as plain words, for the line the table of
 * contents gives it.
 *
 * The nav cannot use `ask.text_html`: it is a line of text in a narrow
 * column, and the markup in there would have to be taken back out to get
 * the words — which means a parser on the browser's side of the wire, the
 * one thing rendering on the server is for. So the words travel beside the
 * HTML, rendered from the same markdown by the same pass.
 *
 * Sub-questions have none, because the nav does not list them.
 */
nav_text: string, };

/**
 * The agent's reasoning, rendered.
 */
export type Reasoning = { 
/**
 * The turn's place in the conversation, counted from 1.
 */
id: number, html: string, };

/**
 * What became of a registration.
 *
 * The refusals are the server's and not the form's: a check the browser made
 * is a courtesy, and every request reaching this endpoint is decided here
 * whether or not a form was involved.
 */
export type Registered = "Added" | "NotAbsolute" | "Missing" | "OutsideWatchedPaths" | "NotARepository" | "NoDefaultBranch" | "AlreadyRegistered";

/**
 * A repository the human is asking Verkstead to take on, named by its absolute
 * path.
 *
 * A path and nothing else: the name and the default branch are read off the
 * repository rather than claimed, for the same reason the CLI derives a Set's
 * `project` and `branch` instead of trusting them.
 */
export type Registration = { path: string, };

/**
 * One row of the Repo list.
 *
 * The path is the resolved one the server recorded rather than whatever was
 * typed to register it: that is the directory Verkstead will actually work in,
 * so it is the one worth showing.
 */
export type RepoEntry = { id: number, name: string, path: string, default_branch: string, };

/**
 * The submitted collection of Answers and Unanswered markers for one Question
 * Set, plus an optional set-level comment — and, on a Set carrying a proposal,
 * the direction the human picked.
 *
 * The invariant is explicitness, not completeness: every Question and
 * Sub-question in the Set appears in `answers` one way or the other, so the
 * agent cannot silently miss a question the human left open. A Response whose
 * every entry is Unanswered carries no Answers at all — with a comment, that
 * is the counter-question that redirects the discussion.
 */
export type Response = { 
/**
 * One entry per Question and Sub-question in the Set.
 */
answers: Array<Answer>, 
/**
 * What the human wants to say about the Set as a whole.
 */
comment?: string | null, 
/**
 * How the human chose to have the work built, on the one Set that carries
 * a [`crate::set::Proposal`].
 *
 * A field of its own rather than an ordinary Answer, because it answers no
 * Question: the chooser is the viewer's, injected onto any Set carrying a
 * proposal, and the three directions it offers are the same three every
 * time. An Answer here would be a Question the agent never asked and would
 * have to be excluded from every rule that counts them.
 *
 * Picking is the whole of accepting the proposal. Every other way of
 * answering sends it back — an answer in the human's own words, questions
 * left open, anything without a pick — so `None` on a proposal Set is the
 * human disagreeing, and `None` anywhere else is every ordinary Response.
 */
direction?: Direction | null, };

/**
 * What became of pressing Resume.
 *
 * Named the way [`GrillingStarted`]'s refusals are, and for a reason of its
 * own on top of theirs: Resume is never silent. Either something is running —
 * which needs no announcement, the session showing up on the Timeline — or
 * nothing is, and the one place that can say why is the answer to the press.
 * A recompute that quietly found nothing to launch is exactly the failure this
 * whole feature is replacing.
 */
export type Resumed = "Resumed" | "NoSuchConversation" | "NotDriven" | "AlreadyDriven" | "NowhereToWork" | "WorktreeRefused" | "NoDirection" | "NothingToWork" | "NoGrillingPairing" | "NoImplementationPairing";

/**
 * One session's Screen: the grid its Capture leaves on a terminal.
 *
 * Not the bytes and not a picture of them — the escape sequences that would
 * paint the grid as it stands, which is what the terminal in the details pane
 * is fed. The server holds the terminal that decided them and hands over the
 * repaint; the browser's copy is a window onto that one rather than a second
 * opinion about it (ADR 0007).
 *
 * The size comes with it because a repaint means nothing without one: the same
 * sequences put a session's display in different places on a grid of a
 * different width.
 */
export type Screen = { repaint: string, columns: number, rows: number, };

/**
 * One stored Question Set as the browser receives it: the document where this
 * build can still read what was asked, and the record itself where it cannot.
 *
 * A tagged kind rather than a `SetView` with everything nulled out, because the
 * two are read for different things. One is a Set to answer or a decision to
 * read back; the other is a body nobody here can render, kept so that what was
 * asked is not lost — see [`UnreadableSet`]. A page that had to work out which
 * it was holding from a field being null would be a page that could draw a
 * sheet over a Set it cannot read.
 */
export type SetReading = { "Set": SetView } | { "Unreadable": UnreadableSet };

/**
 * One row of a Question Set's Timeline table: the number it answers to, what
 * was asked, and what was decided.
 *
 * Plain words in both columns rather than the rendered HTML the Set page draws.
 * A row is one line in a list of Events — the markup would have to come back
 * out to fit, which means a parser on the browser's side of the wire, the one
 * thing rendering on the server is for.
 */
export type SetRow = { 
/**
 * `Q7` for a Question, `Q7a` for a Sub-question.
 */
name: string, 
/**
 * Whether this row is a Sub-question, so the table can indent it under the
 * Question it belongs to.
 */
nested: boolean, 
/**
 * What was asked, as plain words.
 */
question: string, 
/**
 * What was decided, as plain words: the Option that was chosen, whatever
 * was written, or both. Empty where nothing was — a Question left open, a
 * Heading that asked nothing, or a Set still waiting on the human. Which of
 * those it is, the Set's `standing` says.
 */
answer: string, };

/**
 * One Question Set as the browser receives it.
 *
 * Everything the agent wrote — the Preface, every Question's and Sub-question's
 * text, every Option's, and the Postscript — arrives as HTML rather than as its
 * source, and so does the Diff: the server has the markdown parser and the diff
 * highlighter, and this way the browser needs neither.
 */
export type SetView = { id: number, 
/**
 * The Conversation this Set was asked from — where it lives, and what a
 * page reached by the Set's own id leads back to.
 *
 * It travels with the Set rather than being looked up beside it, because a
 * page opened from a push notification knows the Set and nothing else, and
 * a way back that arrived a moment later would be a page that briefly led
 * nowhere.
 */
conversation: number, title: string, project: string | null, branch: string | null, preface_html: string | null, diff: DiffView | null, questions: Array<QuestionView>, 
/**
 * What the agent closed the Set with, for the page to draw above the
 * set-level comment box. Rendered here like the Preface, because it is the
 * same kind of thing said at the other end of the Set.
 */
postscript_html: string | null, 
/**
 * Whether anything the agent wrote here came out as a Diagram, and so
 * whether this page carries the client-side renderer at all.
 *
 * Answered by the server, from the HTML it has just rendered — see
 * `diagrammed`. It travels with the Set because it is a fact about this
 * Set's own material, and because it decides what the page names in its
 * head, which is written before anything in the browser could ask.
 */
diagrams: boolean, 
/**
 * Where the Set stands. It decides whether this page is a form or a record,
 * so it travels with the Set rather than being fetched once the page is
 * already up.
 */
standing: Standing, 
/**
 * The wrap-up proposal this Set carries, on the one Set that carries one.
 *
 * What the page draws the direction chooser from: the recommendation to
 * mark, and the reasoning to put beside the three choices. `null` on every
 * ordinary Set, which is what leaves the chooser off it.
 *
 * It travels with the Set rather than being looked up beside it for the
 * reason the Conversation does: the decision and what it is a decision
 * about arrive together, so the page never draws the Questions above a
 * chooser that has not turned up yet.
 */
proposal: ProposalView | null, };

/**
 * The settings as the human has just written them.
 *
 * The author fields and the token travel together because the page saves as
 * one — and the token's half is an action rather than a value, because most
 * saves are not about the token at all.
 */
export type SettingsEdit = { git_author: Author, github_token: TokenEdit, };

/**
 * What became of a save.
 *
 * No refusals to name: there is nothing about a name, an address or a token
 * this server declines to write down, and a file it could not write at all is
 * the one failure — which is a status code, because it is something to try
 * again rather than something to read.
 */
export type SettingsSaved = { 
/**
 * How the settings stand now, read back off the files rather than echoed
 * from what came in — the files are the source of truth, and a hand-edit
 * made a moment ago is part of what the page should be showing.
 */
settings: SettingsView, 
/**
 * What GitHub made of the token that was just saved, or `null` where the
 * save was not about a token.
 */
verified: Verified | null, };

/**
 * The settings as they stand, read off the two files at the moment they are
 * asked for.
 */
export type SettingsView = { git_author: Author, 
/**
 * What can be said about the configured token, or `null` where there is
 * none — which is what a Verkstead nobody has told anything looks like.
 */
github_token: TokenSaved | null, };

/**
 * Whether the sidebar is drawing what the human has archived.
 *
 * Their standing choice rather than this device's: it is read back off the
 * server on every load, and what is sent when the toggle is flipped is the
 * position it has been put in rather than the flip itself — a switch says
 * where it stands, and saying it twice says the same thing.
 */
export type ShowingArchived = { 
/**
 * On: the archived Conversations are on the list, in their ordinary
 * places. Off: they are not drawn at all.
 */
showing: boolean, };

/**
 * What the server says down a live Screen's socket.
 *
 * Watching a running session is the one place the viewer is sent something
 * rather than fetching it, so the two things it can be sent say which they are
 * rather than being told apart by shape. A repaint arrives first and whenever
 * the grid has been resized under everybody; what the session printed arrives
 * as it prints it.
 */
export type Shown = { "Painted": Screen } | { "Printed": string };

/**
 * How big a Screen is, in characters.
 *
 * Named for the Screen rather than for the window it was measured in, because
 * that is what it becomes: a watcher reports the size of the pane it drew, and
 * the latest one is the size the Screen and the session's own terminal are.
 */
export type Size = { columns: number, rows: number, };

/**
 * One stage of a roadmap: the number it answers to, what it is called, and
 * whether it is done.
 */
export type StageEntry = { 
/**
 * As the roadmap writes it, zero-padding and all — `01`.
 */
number: string, title: string, 
/**
 * Whether the stage is finished, which here *is* the checkbox: a stage's
 * brief stays where it is for ever, being the record of what the stage was
 * for, so there is no file going away to read it off. The other way round
 * from a task — see [`TaskEntry::done`].
 */
done: boolean, };

/**
 * The roadmap as the Timeline shows it: what it is called, and every stage
 * against whether it is checked.
 *
 * No id and no stamp of its own, for the reason the task list beside it has
 * none: it is read out of `docs/roadmaps/` each time the Conversation is, so
 * what it says is what the Worktree holds now. The moment the roadmap landed is
 * stamped all the same — see [`StageListReached`]. Nothing opens it either —
 * the whole of a stage list is the list.
 */
export type StageListEvent = { 
/**
 * The roadmap's directory under `docs/roadmaps/` — `mvp` — which is its
 * identity: what a stage's brief sits beside, and what whoever starts the
 * next stage is pointed at.
 */
name: string, 
/**
 * `ROADMAP.md`'s own heading, which is prose the roadmap wrote about
 * itself. Empty where it wrote none.
 */
title: string, 
/**
 * In the order the roadmap has them, which is the order they get worked in.
 */
stages: Array<StageEntry>, };

/**
 * The roadmap on the record: where it landed, and what it says now.
 *
 * The stage lists rather than one, because a branch may have written to more
 * than one roadmap and the pinned block draws each of them. Empty where there
 * is nothing left to read, exactly as the backlog's is.
 */
export type StageListReached = { id: number, 
/**
 * When the roadmap landed, RFC 3339.
 */
at: string, roadmaps: Array<StageListEvent>, };

/**
 * How a Set stands: still waiting on the human, answered, or closed unanswered.
 */
export type Standing = { "Waiting": Liveness } | { "Answered": Answered } | { "LockedUnanswered": string };

/**
 * What became of starting one.
 */
export type Started = { "Started": { id: number, } } | "NoSuchRepo";

/**
 * A steer as the page receives it: when, where the human sent it, and what
 * they wrote to send it there with.
 *
 * The one Event that is sometimes a move and sometimes a document. A steer
 * into Wrapping or Done says nothing but the state, like the move it stands
 * above; a steer into Implementing carries the instruction the session was set
 * going on, which is the whole of what that session was asked to do. A steer
 * into Grilling carries a document too, and that one arrives as a Brief Event
 * of its own — it opens a round, and a round starts from a Brief.
 */
export type SteerEvent = { id: number, 
/**
 * When it was steered, RFC 3339.
 */
at: string, 
/**
 * The state the human moved it into.
 */
target: Lifecycle, 
/**
 * The instruction they steered it with, rendered and sanitized on the way
 * out as every piece of markdown on this wire is — and `None` for every
 * steer that carried nothing written.
 */
html: string | null, };

/**
 * What clicking Steer found, which is what the modal it opens is drawn from.
 *
 * The click is a press of its own rather than the first half of the submit: it
 * stops the drive before the modal opens, so that nothing new is launched while
 * the human composes and the world the modal was drawn against is the world the
 * submit arrives in. Cancel leaves the Conversation stopped with Resume on
 * offer, which is accepted rather than a bug — the click is what freezes it.
 */
export type SteerOpened = { "Opened": { 
/**
 * Whether a session is still running as the modal opens.
 *
 * What **Interrupt current task** is offered for: the click leaves what
 * is running exactly where it is, and the checkbox is the only way to
 * end it where it stands. What ends it otherwise is the submit's own
 * launch — one Worktree holds one agent, so the session a steer starts
 * takes the Worktree from whatever is still in it — and into Done,
 * where nothing is launched, nothing ends it at all.
 *
 * Where nothing is running there is nothing to interrupt, so the
 * checkbox is not drawn at all.
 */
working: boolean, } } | "NoSuchConversation";

/**
 * What the human settled in the modal: where the Conversation goes, what runs
 * the work there, and what to do about anything still running.
 */
export type SteerSubmission = { 
/**
 * Which state to move it into.
 */
target: SteerTarget, 
/**
 * Whether to end the session that is running where it stands.
 *
 * `false` is the default and the ordinary case: the click stopped the
 * drive, so nothing was started after what is running, and what ends it is
 * this steer's own launch taking the Worktree from it. `true` is the human
 * saying they will not wait for it — which is what saves the wait where the
 * launch would have had to queue behind it, and what ends it at all into
 * Done, where nothing is launched.
 */
interrupt: boolean, 
/**
 * The Pairing the work runs under from here, for a target something runs
 * in — and what is picked is recorded as the *Conversation's*, because
 * steering re-settles what runs the work rather than picking for one
 * session.
 *
 * Absent where the target runs nothing, and absent where the human left
 * the picker on what the Conversation already had: both are a submit that
 * changes no Pairing. A Conversation with none fixed yet — a steered draft
 * — is why the pick is part of the modal rather than an error path, and one
 * that arrives with neither this nor a Pairing of its own is refused by
 * name.
 */
pairing: ProfileChoice | null, 
/**
 * The new round's Brief, for a steer into Grilling.
 *
 * It lands as a Brief Event of its own, frozen the moment it does: a Brief
 * freezes when its round leaves Draft, and a round steered into has no
 * Draft to leave. A second Brief beside the first rather than an edit of
 * it — what the earlier round was built from stays on the record.
 *
 * Absent is the ordinary case and not a refusal: the session starts on the
 * Brief that is already there, and the steer leaves nothing but its own
 * Event behind.
 */
brief: string | null, 
/**
 * The hand-written work, for a steer into Implementing.
 *
 * It lands as the Steer Event's own body and a session is started on it —
 * a driver of the Conversation rather than an errand beside it, so what
 * follows a clean finish is whatever the branch then holds.
 *
 * **Required where nothing stands to be carried on**, and optional beside
 * carrying on where something does: a branch with a backlog left in it has
 * an answer to what is next, and a branch with nothing on it has none. A
 * submit that names Implementing with neither is refused by name — see
 * [`ConversationSteered::NoInstruction`].
 *
 * Whitespace alone is nothing written, exactly as the brief above it: a
 * textarea somebody tabbed through is not an instruction.
 *
 * Nothing anywhere else reads it. A target that starts no session has
 * nothing to write an instruction for.
 */
instruction: string | null, 
/**
 * Whether the session is primed with everything the human has already
 * answered.
 *
 * The digest a relaunched grilling assembles for itself — every answered
 * Question Set of the Conversation, in the order it was asked — offered
 * here as a choice rather than always sent. A fresh brief is often the
 * point of the steer, and priming it with the whole of the last interview
 * would be steering into the argument that has just been left behind.
 *
 * Nothing anywhere else reads it: a target that starts no grilling starts
 * nothing to prime.
 */
digest: boolean, };

/**
 * Where a steer can send a Conversation.
 *
 * Draft and Closed are not among them and never will be: each has a way in of
 * its own, and a steer is for the four states the work is *done in*. A target
 * the modal offers is a target something can be set going in, which is why
 * Wrapping is offered only where the work is already on a pull request — the
 * one of the four that is drawn out at all, an instruction being writable
 * anywhere and Done needing nothing.
 */
export type SteerTarget = "Grilling" | "Implementing" | "Wrapping" | "Done";

/**
 * What became of the human's Response.
 */
export type Submitted = "Accepted" | "AlreadyAnswered" | "NoSuchSet" | "Locked" | { "Rejected": Array<string> };

/**
 * What became of a device asking to be notified.
 */
export type Subscribed = "Stored" | "Incomplete";

/**
 * A subscription as `PushManager.subscribe` describes one, flattened to the
 * three things a push needs: where to send it, and the two keys it is
 * encrypted for.
 *
 * Flattened rather than passed through as the browser's own JSON, because the
 * nesting it uses — `keys.p256dh`, `keys.auth` — is the browser's shape and not
 * something the server has any reason to learn.
 */
export type Subscription = { endpoint: string, p256dh: string, auth: string, };

/**
 * One task of a backlog: the number it answers to, what it is called, and
 * whether it is done.
 */
export type TaskEntry = { 
/**
 * As the list writes it, zero-padding and all — `01`. A Timeline that
 * renumbered the backlog would be showing its own list rather than the
 * repository's.
 */
number: string, title: string, 
/**
 * Whether the task is finished, which is the task file having gone from
 * `.tasks/`. That is the done-signal the task runner turns on, and a
 * checkbox is how an entry is written rather than what says it is done.
 */
done: boolean, };

/**
 * The backlog as the Timeline shows it: what the work is called, and every
 * task against whether it is done.
 *
 * No id and no stamp of its own. It is read out of `.tasks/` each time the
 * Conversation is — the repository owns the files, and Verkstead never does —
 * so what it says is what the Worktree holds now rather than what it held at
 * any one moment.
 *
 * Which does not keep it off the record. The moment a backlog *landed* is worth
 * stamping and is stamped — see [`TaskListReached`], which carries this reading
 * at that row — so the identity is on the row and the content is here, and the
 * card is the same card in both places.
 *
 * Nothing opens it: the whole of a task list is the list, which is why the
 * design gives it no details pane.
 */
export type TaskListEvent = { 
/**
 * What the backlog is called: `TODO.md`'s heading, which is the feature
 * name the breaking-down session picked. Empty where it wrote none.
 */
feature: string, 
/**
 * In the order the list has them, which is the order they get worked in.
 */
tasks: Array<TaskEntry>, };

/**
 * The backlog on the record: where it landed, and what it says now.
 *
 * The two halves come from different places on purpose. `id` and `at` are the
 * row's, stamped once when the branch first carried a backlog; `list` is the
 * Worktree's, read afresh every time the Conversation is — so the card ticks
 * along with the work while the row it sits at stays where it was.
 */
export type TaskListReached = { id: number, 
/**
 * When the backlog landed, RFC 3339.
 */
at: string, 
/**
 * The backlog as it stands, or nothing where there is none to read: a
 * Worktree that has been taken away, or a `.tasks/` the branch has since
 * finished with. The row stays either way — it is the record of a moment,
 * and the moment happened.
 */
list: TaskListEvent | null, };

/**
 * One entry in a Timeline.
 *
 * A tagged kind rather than a struct with a nullable field per kind: what the
 * details pane draws is decided by which kind an Event is, and the stages after
 * this one add their kinds here.
 */
export type TimelineEvent = { "Brief": BriefEvent } | { "Moved": MovedEvent } | { "AgentOutput": AgentOutputEvent } | { "QuestionSet": QuestionSetEvent } | { "UnreadableSet": UnreadableSetEvent } | { "Handoff": HandoffEvent } | { "Commit": CommitEvent } | { "Notice": NoticeEvent } | { "ManualTask": ManualTaskEvent } | { "Steer": SteerEvent } | { "PullRequest": PullRequestEvent } | { "TaskList": TaskListReached } | { "StageList": StageListReached };

/**
 * What is to become of the configured token.
 */
export type TokenEdit = "Keep" | { "Set": { token: string, } } | "Clear";

/**
 * Everything about the configured token that is not the token.
 */
export type TokenSaved = { 
/**
 * Its last four characters — fewer, for a token shorter than that, which
 * is a hand-edit rather than anything GitHub issued.
 */
last_four: string, 
/**
 * When the secrets file was last written, RFC 3339. The file's own
 * modification time rather than a stamp stored beside the token: the file
 * is the source of truth, and a hand-edit that moved the token would leave
 * a stored stamp saying the wrong day.
 */
at: string, };

/**
 * What a tool answered.
 */
export type ToolResult = { 
/**
 * The turn's place in the conversation, counted from 1.
 */
id: number, 
/**
 * The call this answers, by the name the backend gave it. Empty where the
 * log gave none, which leaves the answer standing on its own.
 */
call: string, 
/**
 * Whether the tool failed.
 */
failed: boolean, 
/**
 * What it said, as it said it.
 */
text: string, };

/**
 * A tool call, as one line plus what it was called with.
 */
export type ToolUse = { 
/**
 * The turn's place in the conversation, counted from 1.
 */
id: number, 
/**
 * What the tool is called.
 */
name: string, 
/**
 * The name the backend gave this call, which its answer names back. Empty
 * where the log gave none, which leaves the call with nothing to pair it
 * to — still a call, still shown.
 */
call: string, 
/**
 * The one line about it. Empty where the call said nothing this could
 * summarise, which leaves the name standing on its own.
 */
about: string, 
/**
 * What it was called with, whole.
 */
input: string, };

/**
 * One session's Transcript as the details pane receives it — the whole of it,
 * or whatever of it lies past where the pane's last reading stopped.
 */
export type TranscriptView = { 
/**
 * The conversation, in the order it happened.
 */
turns: Array<Turn>, 
/**
 * Everything that was not the conversation.
 */
bookkeeping: Array<Bookkeeping>, 
/**
 * Whether this is the record from its beginning, rather than a piece of it
 * to add to what the reader already has.
 *
 * The reader cannot tell from the payload and must not guess: a reading
 * that was asked to carry on from a cursor and could not falls back to the
 * whole record, which is always a correct answer — and appending one of
 * those to what was already drawn would be drawing the beginning twice.
 */
whole: boolean, 
/**
 * Where this reading stopped, to be handed back to ask for what comes
 * after it. Opaque to whoever holds it: it is the server's own bookmark,
 * and the shape of it is [`Cursor`]'s business alone.
 */
cursor: string, };

/**
 * One thing that was said, or done, or put.
 *
 * Flat on the wire — `{"id": 3, "kind": "Prose", "html": "…"}` — rather than
 * wrapped in the variant's name, because the viewer reconciles turns by `id`
 * and reconcile reads its key off the element itself: an id one level down
 * would match nothing and fall back to matching by position, silently.
 */
export type Turn = { "kind": "Prose" } & Prose | { "kind": "Reasoning" } & Reasoning | { "kind": "ToolUse" } & ToolUse | { "kind": "ToolResult" } & ToolResult | { "kind": "Put" } & Put | { "kind": "Unread" } & Unread;

/**
 * A line nothing here knows how to draw.
 */
export type Unread = { 
/**
 * The turn's place in the conversation, counted from 1.
 */
id: number, line: string, };

/**
 * A stored Set this build cannot deserialize, as the browser receives it: the
 * stored body, and what reading it came to.
 *
 * The body verbatim rather than rendered — there is nothing here that knows
 * what it means, which is the whole of what is wrong — so the page draws it as
 * the JSON it is. Nothing rewrites it: a later Verkstead that can read it again
 * should find it exactly as the agent sent it.
 *
 * No `standing` and no title. Answering is checked against Questions nobody
 * here can read, so it is not offered, and neither is locking; and what the
 * Set was called is in the body along with everything else, said once rather
 * than half-recovered into a heading.
 */
export type UnreadableSet = { id: number, 
/**
 * The Conversation it was asked from — the way back, which an unreadable
 * Set needs exactly as a readable one does.
 */
conversation: number, 
/**
 * The stored JSON, byte for byte.
 */
body: string, 
/**
 * What deserializing it said.
 */
why: string, };

/**
 * A Question Set the Timeline cannot draw a table for, because this build
 * cannot read the body it was stored as.
 *
 * What it carries is the reason and no more. There is no title — that is in the
 * body with everything else — and no standing, because a Set nobody here can
 * read is not one anybody is going to answer. The stored body itself is what
 * the details pane fetches, through the same `/api/ui/sets/{id}` a readable Set
 * is opened by: it is the same Set reached the same way, and what comes back
 * says which of the two it is.
 */
export type UnreadableSetEvent = { id: number, 
/**
 * When the Set was put, RFC 3339.
 */
at: string, set_id: number, 
/**
 * What deserializing the stored body said. On the row rather than behind
 * the fetch, because it is one line and it is the whole of what happened:
 * a reader who has to open the Event to find out why a row says nothing has
 * been told nothing by the row.
 */
why: string, };

/**
 * A device asking not to be told any more, named by its endpoint — which is the
 * only name a subscription has.
 *
 * An endpoint the server never stored is not an error: a browser can drop its
 * own subscription without the server having heard of it, and afterwards what
 * was asked for holds either way — nothing is sent there.
 */
export type Unsubscribe = { endpoint: string, };

/**
 * Whether there is a newer Verkstead to update to.
 */
export type UpdateNotice = "Current" | { "Available": { version: string, } };

/**
 * Who a token authenticates as, or why nobody could be asked.
 *
 * The failure is an answer here rather than a failed save. A token is pasted
 * once, out of a page on GitHub that will not show it again, and a network
 * that was briefly down is no reason to make the human go back for another
 * one: the token is written down, and this says what happened when it was
 * tried.
 */
export type Verified = { "Account": { login: string, } } | { "Refused": { why: string, } };

/**
 * One way a Set fails the question grammar.
 */
export type Violation = { 
/**
 * The question at fault, e.g. `Q7` or `Q7a`. Absent when the problem is
 * the Set as a whole.
 */
label?: string | null, message: string, };

/**
 * And what a watcher says back up it.
 *
 * Two kinds of thing, each saying which it is: the socket is a conversation in
 * both directions, and what a watcher does to a Screen is look at it a
 * different size, or put something into it.
 */
export type Watching = { "Resized": Size } | { "PutIn": string };

/**
 * A Conversation's worktree: where it is, and whether it is still there.
 */
export type Worktree = { path: string, 
/**
 * Whether the directory has gone from under Verkstead.
 *
 * A thing to say rather than a thing to fail on later. A worktree is an
 * ordinary directory on a machine the human also uses, and one that has
 * been deleted by hand should read as a Conversation with a problem — not
 * as an obscure failure from whatever next tries to work in it.
 */
missing: boolean, };
