// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stored Question Set as the browser receives it: the document where this
 * build can still read what was asked, and the record itself where it cannot.
 *
 * A tagged kind rather than a `SetView` with everything nulled out, because the
 * two are read for different things. One is a Set to answer or a decision to
 * read back; the other is a body nobody here can render, kept so that what was
 * asked is not lost — see [`UnreadableSet`]. A page that had to work out which
 * it was holding from a field being null would be a page that could draw a
 * sheet over a Set it cannot read.
 */
export type SetReading = { "Set": SetView } | { "Unreadable": UnreadableSet };
