// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which coding agent a Profile runs.
 *
 * One value. It is on the wire so that a second backend is a variant added
 * beside `Claude` rather than a field the viewer has to start being told about.
 */
export type AgentType = "Claude";

/**
 * One question's slot in a Response: either an Answer — a selected Option
 * and/or free text — or the Unanswered marker, saying the human chose to
 * leave the question open.
 */
export type Answer = { 
/**
 * The question this resolves, by the name it answers to: `Q7` for a
 * Question, `Q7a` for a Sub-question.
 */
label: string, 
/**
 * The number of the Option the human picked.
 */
selected?: number | null, 
/**
 * What the human wrote in their own words, alongside or instead of an
 * Option.
 */
free_text?: string | null, 
/**
 * Left open on purpose. Exclusive with an Answer: the agent must treat
 * the question as still open.
 */
unanswered?: boolean, };

/**
 * A Set's Response as the page needs it: the Answers, and when they were sent.
 */
export type Answered = { submitted_at: string, response: Response, };

/**
 * What the API returns when it refuses a request.
 */
export type ApiError = { 
/**
 * One line saying what was refused.
 */
error: string, 
/**
 * The grammar violations behind the refusal, each naming its question.
 * Empty when the request failed for some other reason.
 */
violations?: Array<Violation>, };

/**
 * One row of the Archive.
 *
 * No Liveness, because nothing is waiting on a settled Set. Its time is
 * worded like the pending list's — an age while the settling is fresh, and
 * the plain date once it is not, because this is a permanent log and old ages
 * stop meaning anything.
 */
export type ArchiveEntry = { id: number, title: string, project: string | null, branch: string | null, settled_at: string, 
/**
 * The minute it was settled, exactly — the tooltip behind the words.
 */
settled_stamp: string, 
/**
 * Whether it got here without a Response — archived unanswered by the
 * human, rather than decided.
 */
unanswered: boolean, };

/**
 * What became of the human closing a Set unanswered.
 */
export type Archived = "Closed" | "AlreadyAnswered" | "AlreadyArchived" | "NoSuchSet";

/**
 * A Question or a Sub-question as the page draws it: the name it answers to,
 * its text already rendered, and the Options it offers.
 *
 * One type for both, because the page asks them the same way and the schema's
 * distinction between them is spent by the time it gets here: a Sub-question's
 * name is its parent's label and its letter, resolved on the way out.
 *
 * The form is built from the Options' numbers and their Recommendation flags,
 * and a Response answers by number.
 */
export type AskView = { 
/**
 * `Q7` for a Question, `Q7a` for a Sub-question.
 */
name: string, 
/**
 * The text as HTML, rendered and sanitized by the server on the way out.
 */
text_html: string, 
/**
 * The axes the Options are compared along, each already inline HTML, in the
 * order the agent declared them. Empty on a question that declared none —
 * which is what tells the page to draw the list rather than the table, so
 * the two never have to be told apart by looking at the Options.
 *
 * Rendered here beside everything else the agent wrote, so the browser
 * still needs no markdown parser to draw a header.
 */
columns: Array<string>, options: Array<OptionView>, };

/**
 * The commit to branch from, or `null` to go back to the default-branch rule.
 */
export type BaseCommitOverride = { 
/**
 * Whatever names a commit in the repository — a short hash, a tag, a branch
 * — which the server resolves before it records anything.
 */
commit: string | null, };

/**
 * What became of overriding the base commit.
 */
export type BaseRecorded = "Recorded" | "NoSuchConversation" | "NotDrafting" | "NoSuchCommit";

/**
 * What the branch is to be called.
 */
export type BranchRename = { branch: string, };

/**
 * What became of naming the branch.
 */
export type BranchRenamed = "Renamed" | "NoSuchConversation" | "NotDrafting" | "NotABranchName";

/**
 * A Brief as the human has just written it.
 */
export type BriefEdit = { markdown: string, };

/**
 * The Brief as the page receives it: rendered for reading, and as it was
 * written for editing.
 */
export type BriefEvent = { id: number, 
/**
 * When it was written, RFC 3339.
 */
at: string, 
/**
 * The markdown the human last wrote, for the field they write it in.
 */
markdown: string, 
/**
 * The same, as HTML — rendered and sanitized by the server on the way out.
 */
html: string, };

/**
 * What became of an edit to a Brief.
 */
export type BriefSaved = "Saved" | "NoSuchConversation" | "NotDrafting";

/**
 * Why a saved Profile cannot be run under as things stand.
 *
 * Not a way of being saved: every Profile here passed the same checks when it
 * was written down. This is what has become of its pair since.
 */
export type Broken = "DirMissing" | "ConfigMissing" | "OutsideWatchedPaths";

/**
 * One row of the conversations sidebar.
 *
 * The branch is the row's name: a Conversation has no title of its own, and of
 * what it does have the branch is the short line the human chose.
 */
export type ConversationEntry = { id: number, branch: string, 
/**
 * What the Repo this Conversation is against is called.
 */
repo: string, state: Lifecycle, };

/**
 * One Conversation, whole: what it is attached to, what the human has settled
 * about it, and everything that has happened to it.
 */
export type ConversationView = { id: number, 
/**
 * The Repo, in the shape the Repo list already sends one — the workbench
 * shows the same three facts about it, and a second shape for the same
 * thing would be a second opinion about what a Repo is.
 */
repo: RepoEntry, branch: string, 
/**
 * The commit the work will branch from, where the human overrode the rule.
 * `null` is the rule itself: the default branch's tip, as it stands when
 * grilling starts — which is why there is no value here to show instead.
 */
base_commit: string | null, state: Lifecycle, 
/**
 * The Agent Profile the grilling session will run under, whole rather than
 * by id: the pane says what it is, and whether it is still runnable.
 */
grilling_profile: ProfileEntry | null, 
/**
 * And the one the implementation will run under. Chosen separately because
 * it is genuinely a separate account and model.
 */
implementation_profile: ProfileEntry | null, 
/**
 * Whether everything the next stage needs before it will start grilling is
 * settled: both Profiles chosen, and neither of them broken.
 *
 * The server's rule rather than something the page works out from the two
 * fields above, because it is not only about whether they are filled in — a
 * Profile whose pair has gone is not one to launch a session under — and
 * because the stage that grills adds its own conditions to the same answer.
 */
ready_to_grill: boolean, 
/**
 * Oldest first, which is reading order and puts the Brief at the top.
 */
timeline: Array<TimelineEvent>, };

/**
 * The Diff as the browser receives it: the HTML the server rendered, and the
 * path of each file in it, in Diff order — `paths[0]` is what `#diff-1` shows.
 *
 * The two travel together rather than as two fields on the Set, because they
 * describe the same thing and the table of contents is built from both: the
 * nav names the folds from the paths and jumps by their positions, so a nav
 * out of step with the markup would jump to the wrong file. Reading the paths
 * back out of the rendered HTML instead would mean shipping a parser to do it
 * with, and would make the nav a description of the page rather than of the
 * Set.
 */
export type DiffView = { html: string, paths: Array<string>, };

/**
 * Where a Conversation has got to.
 *
 * The whole ladder, though only [`Lifecycle::Draft`] is reachable yet: the
 * states are the domain's, and the page says which one a Conversation is in
 * rather than assuming the only one it can currently be.
 */
export type Lifecycle = "Draft" | "Grilling" | "Direction" | "Implementing" | "Wrapping" | "Done";

/**
 * What the pending list says about a Set: whether an agent is currently
 * waiting on it, or nothing is holding a wait any more.
 *
 * Display state only (ADR-0001). A disconnected Set is still answerable and is
 * never withdrawn on its own — the CLI reconnects through transient drops, and
 * only a human may archive a Set whose agent is really gone.
 *
 * It is a verdict rather than a timestamp because the server has the clock and
 * the registry of held waits; the browser only draws what it is told.
 */
export type Liveness = "waiting" | "disconnected";

/**
 * Starting a Conversation: the Repo it is against, and nothing else.
 *
 * The branch name is not the browser's to send. It is prefilled randomly, and a
 * prefill the page invented would be one the server never saw — the record is
 * the server's from the moment it exists.
 */
export type NewConversation = { repo_id: number, };

/**
 * One Option as the page draws it: the number a Response answers by, its text
 * already rendered, and whether the agent recommended it.
 *
 * Its text is inline markup and nothing blockier, because an Option is one line
 * beside a radio and the whole row is the tap target: a paragraph or a list
 * emitted inside that label would split the row in two.
 */
export type OptionView = { n: number, 
/**
 * The text as inline HTML, rendered and sanitized by the server on the way
 * out.
 */
text_html: string, recommended: boolean, 
/**
 * This Option's row of the Answer Table, one cell per axis the question
 * declared, in that order, each already inline HTML. Empty wherever the
 * question declared no axes.
 *
 * Inline for the reason `text_html` is: the whole row is the tap target,
 * and a block in one of its cells would break the row apart.
 */
cells: Array<string>, };

/**
 * One row of the pending list.
 *
 * The Liveness arrives already decided, like the age: the registry of held
 * waits is the server's, and this way the viewer draws a badge rather than
 * working one out.
 */
export type PendingEntry = { id: number, title: string, project: string | null, branch: string | null, age: string, 
/**
 * The minute the Set arrived, exactly — the tooltip behind the age.
 */
created_stamp: string, liveness: Liveness, };

/**
 * Which Profile a Conversation is choosing for one of its two roles.
 */
export type ProfileChoice = { profile_id: number, };

/**
 * What became of choosing one.
 */
export type ProfileChosen = "Chosen" | "NoSuchConversation" | "NoSuchProfile";

/**
 * What became of removing a Profile.
 */
export type ProfileDeleted = "Removed" | "NoSuchProfile" | "InUse";

/**
 * A Profile as the human has just written it, for saving or for rewriting.
 *
 * No agent type: there is one, and offering a choice of one is theatre. The
 * server records `Claude`, and the field arrives here when there is something
 * to choose between.
 */
export type ProfileEdit = { name: string, 
/**
 * The absolute path of the directory bind-mounted over `~/.claude`.
 */
claude_dir: string, 
/**
 * The absolute path of the file bind-mounted over `~/.claude.json`.
 */
config_file: string, 
/**
 * What a session runs on unless it is told otherwise.
 */
model: string, };

/**
 * One row of the Profile list.
 *
 * The paths are the resolved ones the server recorded rather than whatever was
 * typed to save them: those are what will be bind-mounted, so those are what is
 * worth showing.
 */
export type ProfileEntry = { id: number, name: string, claude_dir: string, config_file: string, model: string, agent_type: AgentType, 
/**
 * `null` while the pair is where it was left, which is the ordinary case.
 */
broken: Broken | null, };

/**
 * What became of saving a Profile.
 *
 * The refusals are the server's and not the form's: the Watched Paths are a
 * security boundary, and every request reaching the endpoint is decided there
 * whether or not a form was involved.
 */
export type ProfileSaved = "Saved" | "NoSuchProfile" | "Nameless" | "Modelless" | "NameTaken" | "DirNotAbsolute" | "DirMissing" | "DirOutsideWatchedPaths" | "NotADirectory" | "ConfigNotAbsolute" | "ConfigMissing" | "ConfigOutsideWatchedPaths" | "NotAFile";

/**
 * The public half of the server's VAPID keypair, base64url-encoded from the
 * uncompressed point — what `PushManager.subscribe` takes as its
 * `applicationServerKey`.
 *
 * The private half stays on the server: this is only how a browser names the
 * server it is subscribing to.
 */
export type PushKey = { key: string, };

/**
 * One Question as the page draws it, with its Sub-questions nested one level
 * under it.
 */
export type QuestionView = { ask: AskView, subquestions: Array<AskView>, 
/**
 * Whether this Question is a Heading — Sub-questions under it and no
 * Options of its own — and so heads them rather than asking anything. The
 * page draws its text without a field, and no Answer comes back for it.
 *
 * Answered here rather than worked out in the browser from the Options and
 * Sub-questions beside it, so that the page and the grammar that refuses a
 * Response cannot come to different readings of the same Set.
 */
heading: boolean, 
/**
 * The Question's own text as plain words, for the line the table of
 * contents gives it.
 *
 * The nav cannot use `ask.text_html`: it is a line of text in a narrow
 * column, and the markup in there would have to be taken back out to get
 * the words — which means a parser on the browser's side of the wire, the
 * one thing rendering on the server is for. So the words travel beside the
 * HTML, rendered from the same markdown by the same pass.
 *
 * Sub-questions have none, because the nav does not list them.
 */
nav_text: string, };

/**
 * What became of a registration.
 *
 * The refusals are the server's and not the form's: a check the browser made
 * is a courtesy, and every request reaching this endpoint is decided here
 * whether or not a form was involved.
 */
export type Registered = "Added" | "NotAbsolute" | "Missing" | "OutsideWatchedPaths" | "NotARepository" | "NoDefaultBranch" | "AlreadyRegistered";

/**
 * A repository the human is asking Verkstead to take on, named by its absolute
 * path.
 *
 * A path and nothing else: the name and the default branch are read off the
 * repository rather than claimed, for the same reason the CLI derives a Set's
 * `project` and `branch` instead of trusting them.
 */
export type Registration = { path: string, };

/**
 * One row of the Repo list.
 *
 * The path is the resolved one the server recorded rather than whatever was
 * typed to register it: that is the directory Verkstead will actually work in,
 * so it is the one worth showing.
 */
export type RepoEntry = { id: number, name: string, path: string, default_branch: string, };

/**
 * The submitted collection of Answers and Unanswered markers for one Question
 * Set, plus an optional set-level comment.
 *
 * The invariant is explicitness, not completeness: every Question and
 * Sub-question in the Set appears in `answers` one way or the other, so the
 * agent cannot silently miss a question the human left open. A Response whose
 * every entry is Unanswered carries no Answers at all — with a comment, that
 * is the counter-question that redirects the discussion.
 */
export type Response = { 
/**
 * One entry per Question and Sub-question in the Set.
 */
answers: Array<Answer>, 
/**
 * What the human wants to say about the Set as a whole.
 */
comment?: string | null, };

/**
 * One Question Set as the browser receives it.
 *
 * Everything the agent wrote — the Preface, every Question's and Sub-question's
 * text, every Option's, and the Postscript — arrives as HTML rather than as its
 * source, and so does the Diff: the server has the markdown parser and the diff
 * highlighter, and this way the browser needs neither.
 */
export type SetView = { id: number, title: string, project: string | null, branch: string | null, preface_html: string | null, diff: DiffView | null, questions: Array<QuestionView>, 
/**
 * What the agent closed the Set with, for the page to draw above the
 * set-level comment box. Rendered here like the Preface, because it is the
 * same kind of thing said at the other end of the Set.
 */
postscript_html: string | null, 
/**
 * Whether anything the agent wrote here came out as a Diagram, and so
 * whether this page carries the client-side renderer at all.
 *
 * Answered by the server, from the HTML it has just rendered — see
 * `diagrammed`. It travels with the Set because it is a fact about this
 * Set's own material, and because it decides what the page names in its
 * head, which is written before anything in the browser could ask.
 */
diagrams: boolean, 
/**
 * Where the Set stands. It decides whether this page is a form or a record,
 * so it travels with the Set rather than being fetched once the page is
 * already up.
 */
standing: Standing, };

/**
 * How a Set stands: still waiting on the human, answered, or closed unanswered.
 */
export type Standing = { "Waiting": Liveness } | { "Answered": Answered } | { "ArchivedUnanswered": string };

/**
 * What became of starting one.
 */
export type Started = { "Started": { id: number, } } | "NoSuchRepo";

/**
 * What became of the human's Response.
 */
export type Submitted = "Accepted" | "AlreadyAnswered" | "NoSuchSet" | "Archived" | { "Rejected": Array<string> };

/**
 * What became of a device asking to be notified.
 */
export type Subscribed = "Stored" | "Incomplete";

/**
 * A subscription as `PushManager.subscribe` describes one, flattened to the
 * three things a push needs: where to send it, and the two keys it is
 * encrypted for.
 *
 * Flattened rather than passed through as the browser's own JSON, because the
 * nesting it uses — `keys.p256dh`, `keys.auth` — is the browser's shape and not
 * something the server has any reason to learn.
 */
export type Subscription = { endpoint: string, p256dh: string, auth: string, };

/**
 * One entry in a Timeline.
 *
 * A tagged kind rather than a struct with a nullable field per kind: what the
 * details pane draws is decided by which kind an Event is, and the stages after
 * this one add their kinds here.
 */
export type TimelineEvent = { "Brief": BriefEvent };

/**
 * A device asking not to be told any more, named by its endpoint — which is the
 * only name a subscription has.
 *
 * An endpoint the server never stored is not an error: a browser can drop its
 * own subscription without the server having heard of it, and afterwards what
 * was asked for holds either way — nothing is sent there.
 */
export type Unsubscribe = { endpoint: string, };

/**
 * Whether there is a newer Verkstead to update to.
 */
export type UpdateNotice = "Current" | { "Available": { version: string, } };

/**
 * One way a Set fails the question grammar.
 */
export type Violation = { 
/**
 * The question at fault, e.g. `Q7` or `Q7a`. Absent when the problem is
 * the Set as a whole.
 */
label?: string | null, message: string, };
