//! What the viewer receives, and the rendering that produces it.
//!
//! Everything an agent writes — the Preface, every Question's and every
//! Option's text, and the Diff — is turned into sanitized HTML here, on the
//! server, before it goes anywhere near a browser. That is the whole point of
//! this crate being its own: the markdown parser, the sanitizer and the syntax
//! highlighter live on one side of the wire, and the viewer receives HTML it
//! only has to put in the page.
//!
//! The rest of what the viewer is handed lives here for the same reason, even
//! where no markdown is involved: a Timeline's Events and the outcomes of
//! answering and archiving are named states the viewer says in words. Taken
//! together these types *are* the viewer's side of the wire, which is what makes
//! this the one crate the TypeScript is generated from — see the `typescript`
//! feature in the manifest.
//!
//! Nothing here knows about the store, the router or the viewer. Given a
//! [`verkstead_schema::QuestionSet`] and where the Set stands, [`set_view`]
//! hands back the [`SetView`] the viewer draws — so whatever is serving that
//! viewer, this is the one place the rendering happens.

mod answering;
mod conversations;
mod profiles;
mod push;
mod repos;
mod settings;
mod transcript;
mod update;
mod view;

pub use answering::{Archived, Submitted};
pub use conversations::{
    AbandonedRepo, AbandonedRoadmap, Adopted, AdoptedStage, AdoptionView, AgentOutputEvent,
    BaseCommitOverride, BaseRecorded, BranchRename, BranchRenamed, BriefEdit, BriefEvent,
    BriefSaved, Capture, Comment, CommitDiff, CommitEvent, CommitSummary, ConversationAborted,
    ConversationEntry, ConversationView, GrillingStarted, HandedBack, HandoffEvent,
    InterruptionEvent, Lifecycle, ManualTaskEvent, ManualTaskStarted, ManualTaskSubmission,
    MovedEvent, NewAdoption, NewConversation, NoticeEvent, PinnedEvent, ProposalView,
    PullRequestComment, PullRequestCommit, PullRequestDetails, PullRequestEvent,
    PullRequestSummary, QuestionSetEvent, Remedy, RemedyChoice, RemedySettled, RemedyTaken, Screen,
    SetRow, Shown, Size, StageEntry, StageListEvent, Started, Stopped, TaskEntry, TaskListEvent,
    TimelineEvent, Watching, Worktree, agent_output_event, brief_event, commit_diff, commit_event,
    handoff_event, interruption_event, manual_task_event, moved_event, notice_event, proposal_view,
    pull_request_details, pull_request_event, question_set_event, stage_list_event,
    task_list_event,
};
pub use profiles::{
    AgentType, Broken, ProfileChoice, ProfileChosen, ProfileDeleted, ProfileEdit, ProfileEntry,
    ProfileSaved,
};
pub use push::{PushKey, Subscribed, Subscription, Unsubscribe};
pub use repos::{Registered, Registration, RepoEntry};
pub use settings::{
    Author, SettingsEdit, SettingsSaved, SettingsView, TokenEdit, TokenSaved, Verified,
};
pub use transcript::{
    Bookkeeping, Cursor, Prose, Put, Reasoning, ToolResult, ToolUse, TranscriptView, Turn, Unread,
    statements, transcript_after, transcript_view,
};
pub use update::UpdateNotice;
pub use view::{Answered, AskView, DiffView, OptionView, QuestionView, SetView, Standing};

pub mod diff;
pub mod markdown;
pub use view::set_view;

// The highlighter is shared by the two renderers above and wanted by nobody
// else: what it produces reaches the page through them, already marked up.
mod highlight;

// Where the TypeScript is written from, which is a test and nothing else: the
// bindings are generated by running one, never by building anything.
#[cfg(all(test, feature = "typescript"))]
mod typescript;
