//! What the viewer receives, and the rendering that produces it.
//!
//! Everything an agent writes — the Preface, every Question's and every
//! Option's text, and the Diff — is turned into sanitized HTML here, on the
//! server, before it goes anywhere near a browser. That is the whole point of
//! this crate being its own: the markdown parser, the sanitizer and the syntax
//! highlighter live on one side of the wire, and the viewer receives HTML it
//! only has to put in the page.
//!
//! The rest of what the viewer is handed lives here for the same reason, even
//! where no markdown is involved: the two lists' rows carry dates the server has
//! already worded, and the outcomes of answering and archiving are named states
//! the viewer says in words. Taken together these types *are* the viewer's side
//! of the wire, which is what makes this the one crate the TypeScript is
//! generated from — see the `typescript` feature in the manifest.
//!
//! Nothing here knows about the store, the router or the viewer. Given a
//! [`verkstead_schema::QuestionSet`] and where the Set stands, [`set_view`]
//! hands back the [`SetView`] the viewer draws — so whatever is serving that
//! viewer, this is the one place the rendering happens.

mod answering;
mod conversations;
mod lists;
mod profiles;
mod push;
mod repos;
mod update;
mod view;
mod when;

pub use answering::{Archived, Submitted};
pub use conversations::{
    BaseCommitOverride, BaseRecorded, BranchRename, BranchRenamed, BriefEdit, BriefEvent,
    BriefSaved, ConversationEntry, ConversationView, Lifecycle, NewConversation, Started,
    TimelineEvent, brief_event,
};
pub use lists::{ArchiveEntry, PendingEntry};
pub use profiles::{
    AgentType, Broken, ProfileChoice, ProfileChosen, ProfileDeleted, ProfileEdit, ProfileEntry,
    ProfileSaved,
};
pub use push::{PushKey, Subscribed, Subscription, Unsubscribe};
pub use repos::{Registered, Registration, RepoEntry};
pub use update::UpdateNotice;
pub use view::{Answered, AskView, DiffView, OptionView, QuestionView, SetView, Standing};
pub use when::{relative_age, settled_age, utc_stamp};

pub mod diff;
pub mod markdown;
pub use view::set_view;

// The highlighter is shared by the two renderers above and wanted by nobody
// else: what it produces reaches the page through them, already marked up.
mod highlight;

// Where the TypeScript is written from, which is a test and nothing else: the
// bindings are generated by running one, never by building anything.
#[cfg(all(test, feature = "typescript"))]
mod typescript;
